### PR TITLE
fix: #995 and #1006, issues with redirect urls

### LINKED ISSUE #1006: 4.x ArcGISIdentityManager does not have its redirectUri property set
I don't think this is exactly the same issue as #995 (apologies if it is). The other issue seems to have more to do with calling `completeOAuth2` with query parameters on the `redirect_uri`, but in this case `completeOAuth2` otherwise works fine. 

After `completeOAuth2` returns a valid `ArcGISIdentityManager`, it does not have its `redirect_uri` property set (and it is marked as a read-only property in the TypeScript definition file, so it cannot be manually set without having to ignore the type error).

Then, when a token expires (or it is invalidated), it does automatically call the token endpoint for a `exchange_refresh_token`, but it doesn't have a `redirect_uri` so the endpoint returns a 400 error (`redirect_uri not specified`). I'm not sure if this is intended design or if we are supposed to be exchanging a token manually.

It's also still possible to set the `redirect_uri` property manually (and ignoring the type errors from modifying a readonly property), which does work and automatically calls the token endpoint with that `redirect_uri` if the token is ever found to be invalid.

### PR DESCRIPTION
**Pull request by patrickarlt**
This fixes both #995 and #1006.

The root cause of #995 was assuming that query params could not be included in oAuth redirect URIs, when in fact they can be. Any query params in the redirect URI are expected to be placed back on the redirect URI in addition to any oauth query params like `code` and `error`. To resolve this you now must pass `redirectUri` in `completeOAuth2()` like you did in 3.x. This was still documented that was but some demo code committed it. I left the existing code path in for people who leave out `redirectUri`.

To resolve #1006 we now properly set `redirectUri` on the instance of `ArcGISIdentityManager` in `beginOAuth2()`, `completeOauth2()` and `fromToken()` when it is provided. `canRefresh()` now also checks for `redirectUri` since if it isn't defined you cannot exchange refresh tokens.

This also fixes a bug where if you did pass an invalid redirect URI or client id to `completeOauth2()` in a popup it would not register it as an error.

The changes to the browser oauth demo are just prettier + adding the redirect URL to the popup page.

### CODE REVIEW

**Review by dbouwman — APPROVED** [review]
I'm no guru on how oauth is implemented in this library, but this seems like a good fix

**Review by tomwayson — APPROVED** [review]
Nice work @patrickarlt. 

Should I start an issue for v5 deprecations and include "support for calling `completeOAuth2()` w/o a `redirectUri`"?

**Review by gavinr — APPROVED** [review]

File: packages/arcgis-rest-request/src/ArcGISIdentityManager.ts [hunk 1]
```diff
@@ -435,7 +458,7 @@ export class ArcGISIdentityManager implements IAuthenticationManager {
       if (popup) {
         // If we are authenticating a popup we need to return a Promise that will resolve to an ArcGISIdentityManager later.
         return new Promise((resolve, reject) => {
-          // Add an event listener to listen for when a user calls `ArcGISIdentityManager.completeOAuth2()` in the popup.
+          // Add an event listener to listen for when a user calls `ArcGISIdentityManager.completeOAuth2()()` in the popup.
```
Comment (patrickarlt) [inline packages/arcgis-rest-request/src/ArcGISIdentityManager.ts:461]:
```suggestion
          // Add an event listener to listen for when a user calls `ArcGISIdentityManager.completeOAuth2()` in the popup.
```
