### PR TITLE
docs(arcgis-rest-portal): fix incorrect documentation for searchGroupContent

### LINKED ISSUE #1205: Improve documentation for SearchGroupContent()
### Description

Docs for this method are incorrect https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-portal/searchGroupContent/ this should pass an options object with a `q` and `groupId` parameter. The `q` param also should be required.

### Link to page

_No response_

### PR DESCRIPTION
**Pull request by DoiMayank**
### What
This PR fixes the incorrect documentation for the `searchGroupContent` method in the `arcgis-rest-portal` module. The previous documentation incorrectly suggested passing a string as a parameter, but the method actually requires an `options` object containing `q` and `groupId`.

### Why
The current documentation is misleading, causing confusion for developers trying to use this method correctly. This fix ensures the documentation aligns with the method's expected behavior.

### How
- Updated the JSDoc comment for the `searchGroupContent` function in `packages/arcgis-rest-portal/src/search.ts`.
- Updated the example to correctly demonstrate passing an `options` object.

### Context
Fixes #1205
Reference: [searchGroupContent REST Documentation](https://developers.arcgis.com/rest/users-groups-and-items/group-content-search.htm)

### Checklist
- [x] Updated the JSDoc comments for `searchGroupContent`.
- [x] Verified that the changes align with the REST documentation.
- [x] Ran `npm test` to ensure no existing functionality is broken.

### CODE REVIEW

File: packages/arcgis-rest-portal/src/groups/search.ts [hunk 1]
```diff
@@ -36,12 +36,20 @@ export function searchGroups(
...
  *
- * searchGroupContent('water')
- *   .then(response) // response.total => 355
+ * searchGroupContent({
+ *   q: 'water',
+ *   groupId: 'abc123'
+ * })
+ *   .then(response => {
+ *     console.log(response.total); // response.total => 355
+ *   });
```
Comment (gavinr-maps) [inline packages/arcgis-rest-portal/src/groups/search.ts:45]: This section looks good. I think you can remove the `// response.total => 355` line since this is just a fake example the number 355 does not really make sense.

File: packages/arcgis-rest-portal/src/groups/search.ts [hunk 2]
```diff
@@ -36,12 +36,20 @@ export function searchGroups(
...
  * ```
  *
- * @param options - RequestOptions object amended with search parameters.
- * @returns A Promise that will resolve with the data from the response.
+ * @param options - An object containing search parameters.
+ * @param options.q - The search query (required).
+ * @param options.groupId - The ID of the group to search within (required).
+ * @param options.params - Additional search parameters (optional).
```
Comment (gavinr-maps) [inline packages/arcgis-rest-portal/src/groups/search.ts:51]: I do not think you need to add these lines ... the automatic doc generator will link to `ISearchGroupContentOptions` properly as it does currently on https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-portal/searchGroupContent/ : 
image

**Review by gavinr-maps — CHANGES_REQUESTED** [review]
Thanks for the contribution! I have a few comments below. Also, the changes to `CHANGELOG.md` do not look related to this PR .. where did those come from? I think you can probably remove those changes from this PR.

Same for the changes to `package.json` and `package-lock.json` ... I do not think you should make version changes in the PR  - our automatic release system will change those.

**Review by DoiMayank — COMMENTED** [review]
Changes made in search.ts as requested.

Packagae.json, packagae-lock.json and CHANGELOG.md reverted back to original.

**Review by gavinr-maps — APPROVED** [review]
Looks good to me. @patrickarlt is this what you were envisioning for #1205?

**Review by patrickarlt — APPROVED** [review]
Looks great! Thanks @DoiMayank!
