### PR TITLE
B/fix file upload bugs

### LINKED ISSUE #693: Create Item with image is stuck at partial processing
Attempting to create a new Item with an Image. The addItem is successful but the processing says 'partial' and the actual item is not accessible via the Portal REST API

```javascript
Portal.createItem({
      item: {
        title: `SharingImage`,
        type: "Image",
        tags: ["dev","api"],
        typeKeywords: ["Data","Image","png"]
      },
      file: file,
      overwrite: false,
      multipart: true, 
      async: true,
      filename: file.name,
      authentication
    }).then((response) => {
      console.log("Created Item", response)
      this.checkStatus(response.id);
    })
  }
```

responds `{success: true, id: "7f58e9931f394d0894d079b45062c0fe"}`

Here is the request Form data network

```
Request URL: https://www.arcgis.com/sharing/rest/content/users/aturner/addItem
Request Method: POST
Status Code: 200 

Referrer Policy: no-referrer-when-downgrade
:authority: www.arcgis.com
:method: POST
:path: /sharing/rest/content/users/aturner/addItem
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8,he;q=0.7
cache-control: no-cache
content-length: 99560
content-type: multipart/form-data; boundary=----WebKitFormBoundaryMmhFiPDClwvxio9L
origin: http://localui.arcgis.com:9001
pragma: no-cache
referer: http://localui.arcgis.com:9001/iframe.html?id=hub-components--hubupload&viewMode=story
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

Form data
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="f"

json
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="title"

Item_77250
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="type"

Image
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="tags"

dev,api
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="typeKeywords"

Data,Image,png
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="file"; filename="Sharing.png"
Content-Type: image/png


------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="async"

true
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="multipart"

true
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="filename"

Sharing.png
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="overwrite"

false
------WebKitFormBoundaryMmhFiPDClwvxio9L
Content-Disposition: form-data; name="token"

{token removed}
------WebKitFormBoundaryMmhFiPDClwvxio9L--
```

## Multipart commit?

I tried to `commitItemUpload`...

```
Portal.commitItemUpload({
        id: response.id,
        authentication
      })
```

but receive the REST API error response
`{"error":{"code":400,"messageCode":"CONT_0031","message":"Item does not have any parts to commit","details":[]}}`

### PR DESCRIPTION
**Pull request by haoliangyu**
Fix #693, #694, #700 

This PR fixes several file upload bugs based on how the AGO actually uses the APIs. Note that the API docs are not up-to-dated, which leads to bugs.

* Move the `addItemPart` function from the `add.ts` to `upload.ts` for better code organizing
* Adjust the `addItemPart` request URL to be consistent with the actual usage in AGOL
* Adjust the `commitItemUpload` function parameter so it can be used to update item metadata

### CODE REVIEW

File: packages/arcgis-rest-portal/src/items/upload.ts [hunk 1]
```diff
@@ -1,15 +1,65 @@
...
+ * @param requestOptions - Options for the request
+ * @returns A Promise to add the item part status.
+ */
+export function addItemPart(
+  requestOptions?: IItemPartOptions
+): Promise<IUpdateItemResponse> {
+  const partNum = requestOptions.partNum;
+
+  if (!(Number.isInteger(partNum) && 1 <= partNum && partNum <= 10000)) {
+    return Promise.reject(new Error('The part number mustnbe an integer between 1 to 10000, inclusive'))
```
Comment (mikeringrose) [inline packages/arcgis-rest-portal/src/items/upload.ts:44]: spelling `mustnbe`

File: packages/arcgis-rest-portal/src/items/upload.ts [hunk 2]
```diff
@@ -1,15 +1,65 @@
...
+ *
+ * @param requestOptions - Options for the request
+ * @returns A Promise to add the item part status.
+ */
+export function addItemPart(
+  requestOptions?: IItemPartOptions
+): Promise<IUpdateItemResponse> {
+  const partNum = requestOptions.partNum;
+
+  if (!(Number.isInteger(partNum) && 1 <= partNum && partNum <= 10000)) {
```
Comment (mikeringrose) [inline packages/arcgis-rest-portal/src/items/upload.ts:43]: just an opinion, seems clearer to say:
```
if (!Number.isInteger(partNum) || partNum < 1 || parNum > 10000
```

**Comment by haoliangyu** [comment]
@mikeringrose This PR is ready for review.

**Comment by haoliangyu** [comment]
I will add a formatted commit message when squash-and-merge.

**Review by dbouwman — APPROVED** [review]
LGTM, but I'd like @tomwayson to also suss it

File: packages/arcgis-rest-portal/src/items/upload.ts [hunk 3]
```diff
@@ -22,18 +72,22 @@ import {
...
     const url = `${getPortalUrl(requestOptions)}/content/users/${owner}/items/${
-      requestOptions.id
+      requestOptions.item.id
     }/commit`;
 
+    requestOptions.params = {
+      ...requestOptions.params,
+      ...serializeItem(requestOptions.item)
+    };
+
```
Comment (tomwayson) [inline packages/arcgis-rest-portal/src/items/upload.ts:90]: It'd be better to create a new options object rather than mutate `requestOptions` that are passed in.

File: packages/arcgis-rest-portal/src/items/upload.ts [hunk 4]
```diff
@@ -22,18 +72,22 @@ import {
  * ```
  * Commit is called once all parts are uploaded during a multipart Add Item or Update Item operation. See the [REST Documentation](https://developers.arcgis.com/rest/users-groups-and-items/commit.htm) for more information.
  *
- * @param id - The Id of the item to commit upload for.
  * @param requestOptions - Options for the request
  * @returns A Promise to get the commit result.
  */
 export function commitItemUpload(
-  requestOptions?: IUserItemOptions
+  requestOptions?: ICommitItemOptions
```
Comment (tomwayson) [inline packages/arcgis-rest-portal/src/items/upload.ts:79]: this is a breaking change, which is fine if it didn't actually work before.

if it _did_ work before, then we should try to support the previous API and do something like `requestOptions?: ICommitItemOptions | IUserItemOptions` and then internally do something like `const itemId = requestOptions.item ? requestOptions.item.id : requestOptions.id;`

**Review by tomwayson — COMMENTED** [review]
Great work @haoliangyu! 

I left a couple of suggestions. The main thing would be to address the breaking change unless it didn't actually work before.

File: packages/arcgis-rest-portal/src/items/upload.ts (hunk 4 above)
Comment (haoliangyu) [reply packages/arcgis-rest-portal/src/items/upload.ts:79]: Indeed. This function didn't work before, but I agree with your approach to make it compatible with the previous code. Just in case.

Comment (tomwayson) [reply packages/arcgis-rest-portal/src/items/upload.ts:79]: if it didn't work it's ok to leave the breaking change as is

**Review by tomwayson — APPROVED** [review]
nice work @haoliangyu!
